### PR TITLE
MANTA-4926 waferlock README is incorrect

### PR DESCRIPTION
**Pull request by trentm**

### CODE REVIEW

**Review by numericillustration — DISMISSED** [review]
I find this a good update with info about the current mechanism as well as the MANTA-4406 / MANTA-4359 entry content that reflects what I believe is the current state of this tool.  Thanks

**Review by khangngu — COMMENTED** [review]
Trent, can you add more details for the followings:
1)  What are the services that will be added to pg_hba.conf file?  Where is that list kept?
2)  The IP is automatically added or removed from pg_hba.conf when a service is provisioned or de-provisioned

**Comment by numericillustration** [comment]
Noting that we call this pg_hba implementation waferlock v2 and v1 was the ipfilter implementation that was too slow.

**Comment by numericillustration** [comment]
> Trent, can you add more details for the followings:
> 
> 1. What are the services that will be added to pg_hba.conf file?  Where is that list kept?
> 2. The IP is automatically added or removed from pg_hba.conf when a service is provisioned or de-provisioned

Per [these config entries](https://github.com/joyent/waferlock/blob/cc5f20f9546605633d4481640fcc11f9c587977d/sapi_manifests/waferlock/template#L44-L60), the "pg_hba.conf" file on each postgres instance should contain the IP addresses of the trusted hosts for the following services:
ops
pgstatsmon
nameservice
madtom
moray (for the same shard)
postgres (for the same shard)

It updates the pg_hba.conf file as hosts come and go in zk and sapi

the sapi polling interval is configured here https://github.com/joyent/waferlock/blob/cc5f20f9546605633d4481640fcc11f9c587977d/sapi_manifests/waferlock/template#L23-L26 but not sure what the zk polling period is.

**Comment by trentm** [comment]
@khangngu Hopefully answered in the latest commit.

**Review by numericillustration — APPROVED** [review]

**Review by khangngu — APPROVED** [review]

**Pull request merged**
